### ISSUE TITLE
Create example with Accordion and Tables using Bootstrap

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/next-typescript#3]
# Motivation
We want to be able to create a table that contains rows of accordions with a table row as its expandable.

# Task Implementation
- [x] Research React Bootstrap
- [x] Be able to render a table using the Bootstrap component
- [x] Be able to have the table render an accordian as a table row.
- [x] Be able to render inside the accordian the table row as an collapseable.
- [x] Be able to load additional content inside the collapseable.
