### ISSUE TITLE
Extend example with multiple rows

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/next-typescript#6]
# Motivation
We want to expand this example with multiple rows and extend the functionality so that only 1 row is expanded at any point of the app.

# Tasks
- [ ] Render a separate component as a fragment to be able to render the row.
- [ ] Be able to render a list of these row components.
- [ ] Be able to handle an event from each row to designate that it is supposed to be expanded.
- [ ] Be able to handle the event back to the parent.
- [ ] On a click, be able to expand the row.
- [ ] On the click, be able to close the other rows.
